import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

let output = (process.argv.length > 3 && process.argv[3] === '--output-dir') ? process.argv[4] : '.';
output = path.join(output, 'main.js');


esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: output,
}).catch(() => process.exit(1));
